name: CI/CD

on:
  push:
    branches: [master]
    paths-ignore:
      - "debug.ps1"
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]
    paths-ignore:
      - "debug.ps1"
  workflow_dispatch:

jobs:
  ValidatePythonCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('requirements*') }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install --upgrade --upgrade-strategy eager flake8
      - name: Run flake8
        run: flake8 .
  ValidateStaticContent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check JSON files
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
      - name: Markdown lint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
  CreateDockerImage:
    runs-on: ubuntu-latest
    needs: [ValidatePythonCode, ValidateStaticContent]
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the container repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/grillbot/grillbot-docs:master
  DeployToProduction:
    runs-on: ubuntu-latest
    environment: "Production"
    needs: CreateDockerImage
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Execute deployment on SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_Username }}
          password: ${{ secrets.SSH_Password }}
          port: 22
          script: echo '${{ secrets.SSH_Password }}' | sudo -S /scripts/update-grillbot-prod.sh docs
